name = "AVLTrees"
uuid = "4459d02e-7d0b-4014-b2a2-e38a540ff820"
authors = ["krynju <gulinski.krystian@gmail.com>"]
version = "0.3.2"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
