name = "AVL"
uuid = "4459d02e-7d0b-4014-b2a2-e38a540ff820"
authors = ["krynju <gulinski.krystian@gmail.com>"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
